/* tslint:disable */
require("./TcaInteract.module.css");
var styles = {
    tcaInteract: 'tcaInteract_89c04eba',
    header: 'header_89c04eba',
    welcomeTitle: 'welcomeTitle_89c04eba',
    logo: 'logo_89c04eba',
    mainContent: 'mainContent_89c04eba',
    leftColumn: 'leftColumn_89c04eba',
    middleColumn: 'middleColumn_89c04eba',
    rightColumn: 'rightColumn_89c04eba',
    sectionTitle: 'sectionTitle_89c04eba',
    missionSection: 'missionSection_89c04eba',
    missionText: 'missionText_89c04eba',
    missionImage: 'missionImage_89c04eba',
    coreValuesSection: 'coreValuesSection_89c04eba',
    valuesList: 'valuesList_89c04eba',
    valueItem: 'valueItem_89c04eba',
    valueIcon: 'valueIcon_89c04eba',
    valueContent: 'valueContent_89c04eba',
    valueTitle: 'valueTitle_89c04eba',
    valueDescription: 'valueDescription_89c04eba',
    resourceLinksSection: 'resourceLinksSection_89c04eba',
    linksList: 'linksList_89c04eba',
    resourceLink: 'resourceLink_89c04eba',
    linkDescription: 'linkDescription_89c04eba',
    projectSpotlightSection: 'projectSpotlightSection_89c04eba',
    spotlightContent: 'spotlightContent_89c04eba',
    spotlightLocation: 'spotlightLocation_89c04eba',
    spotlightImage: 'spotlightImage_89c04eba',
    spotlightDescription: 'spotlightDescription_89c04eba',
    shoutOutSection: 'shoutOutSection_89c04eba',
    shoutOutCard: 'shoutOutCard_89c04eba',
    avatarContainer: 'avatarContainer_89c04eba',
    avatar: 'avatar_89c04eba',
    nameTitle: 'nameTitle_89c04eba',
    name: 'name_89c04eba',
    title: 'title_89c04eba',
    shoutOutText: 'shoutOutText_89c04eba',
    nominator: 'nominator_89c04eba',
    eventsSection: 'eventsSection_89c04eba',
    eventsList: 'eventsList_89c04eba',
    eventItem: 'eventItem_89c04eba',
    eventDate: 'eventDate_89c04eba',
    socialMediaSection: 'socialMediaSection_89c04eba',
    socialTitle: 'socialTitle_89c04eba',
    socialIcons: 'socialIcons_89c04eba',
    socialIcon: 'socialIcon_89c04eba'
};
export default styles;
/* tslint:enable */ 
//# sourceMappingURL=TcaInteract.module.scss.js.map