/* tslint:disable */
require("./TcaInteract.module.css");
const styles = {
  tcaInteract: 'tcaInteract_dae87d89',
  header: 'header_dae87d89',
  welcomeTitle: 'welcomeTitle_dae87d89',
  logo: 'logo_dae87d89',
  mainContent: 'mainContent_dae87d89',
  leftColumn: 'leftColumn_dae87d89',
  middleColumn: 'middleColumn_dae87d89',
  rightColumn: 'rightColumn_dae87d89',
  sectionTitle: 'sectionTitle_dae87d89',
  missionSection: 'missionSection_dae87d89',
  missionText: 'missionText_dae87d89',
  missionImage: 'missionImage_dae87d89',
  coreValuesSection: 'coreValuesSection_dae87d89',
  valuesList: 'valuesList_dae87d89',
  valueItem: 'valueItem_dae87d89',
  valueIcon: 'valueIcon_dae87d89',
  valueContent: 'valueContent_dae87d89',
  valueTitle: 'valueTitle_dae87d89',
  valueDescription: 'valueDescription_dae87d89',
  resourceLinksSection: 'resourceLinksSection_dae87d89',
  linksList: 'linksList_dae87d89',
  resourceLink: 'resourceLink_dae87d89',
  linkDescription: 'linkDescription_dae87d89',
  projectSpotlightSection: 'projectSpotlightSection_dae87d89',
  spotlightContent: 'spotlightContent_dae87d89',
  spotlightLocation: 'spotlightLocation_dae87d89',
  spotlightImage: 'spotlightImage_dae87d89',
  spotlightDescription: 'spotlightDescription_dae87d89',
  shoutOutSection: 'shoutOutSection_dae87d89',
  shoutOutCard: 'shoutOutCard_dae87d89',
  avatarContainer: 'avatarContainer_dae87d89',
  avatar: 'avatar_dae87d89',
  nameTitle: 'nameTitle_dae87d89',
  name: 'name_dae87d89',
  title: 'title_dae87d89',
  shoutOutText: 'shoutOutText_dae87d89',
  nominator: 'nominator_dae87d89',
  eventsSection: 'eventsSection_dae87d89',
  eventsList: 'eventsList_dae87d89',
  eventItem: 'eventItem_dae87d89',
  eventDate: 'eventDate_dae87d89',
  socialMediaSection: 'socialMediaSection_dae87d89',
  socialTitle: 'socialTitle_dae87d89',
  socialIcons: 'socialIcons_dae87d89',
  socialIcon: 'socialIcon_dae87d89'
};

export default styles;
/* tslint:enable */